source ~/bin/dotfiles/bash/env
source ~/bin/dotfiles/bash/config
source ~/bin/dotfiles/bash/aliases

# private aliases, machine specific, etc
if [ -f ~/bin/dotfiles/bash/paliases ]; then
  source ~/bin/dotfiles/bash/paliases
fi

source ~/bin/dotfiles/git-completion
